=== Good-Shepherd-Lutheran-Church/Good-Shepherd-Lutheran-Church.github.io/persons.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "./persons.schema.json",
	"title": "Data for the church and school staff",
	"description": "An array of objects that contain information about teachers, school administrators, and church staff.",
	"type": "array",
	"items": {
		"type": "object",
		"properties": {
			"name": {
				"type": "string"
			},
			"bio": {
				"type": "string"
			},
			"role": {
				"description": "Departments",
				"type": "array",
				"items": {
					"type": "string",
					"enum": ["churchOffice", "pastor", "teacher", "administrator"]
				},
				"minItems": 1,
				"uniqueItems": true
			},
			"program": {
				"description": "If teacher, what grade do they teach?",
				"type": "array",
				"items": {
					"type": "string",
					"enum": [
						"VPK",
						"Pre-K",
						"Kindergarten",
						"First",
						"Second",
						"Third",
						"Fourth",
						"Fifth",
						"Aftercare",
						"STEM",
						"PE"
					]
				}
			},
			"imageTerm": ["string"]
		},
		"required": ["name", "role"]
	}
}

=== Good-Shepherd-Lutheran-Church/Good-Shepherd-Lutheran-Church.github.io/src/lib/assets/static-data/gslc.persons.json
[
	{
		"name": "Nichole Wester",
		"role": ["teacher"],
		"bio": "Hello! My name is Nichole Wester and I am blessed to be the VPK-C teacher this year at Good Shepherd! I am 42 years young and I live in Tiger Point/Gulf Breeze with my parents, husband, and fur-babies. I've been teaching since 2006 and I feel truly blessed to be able to be a part of the GSLS staff. From the moment I began my career here last year, I felt God'spresence not only in our school but within the heart of our kids. Watching them grow as God's children and knowing that He let me be a small part of that gives me a joy I've never known at other schools.",
		"program": ["VPK", "Aftercare"],
		"imageTerm": "nichole-wester"
	},
	{
		"name": "Brennan Blanchard",
		"role": ["teacher"],
		"bio": "My name is Brennan Blanchard. I was welcomed last year as the STEM teacher for the Spring semester, and I look forward to another opportunity to be part of the GSLS family this year! After moving to Gulf Breeze in 2013, I began teaching preschool when my youngest entered VPK and never looked back. It is truly a blessing to share such a special season in a family’s life when they send their children to school for the first time. Being trusted to help set the tone and lay the foundation for a child’s future school experiences is such important work! When not in the school setting, I am working as a realty agent or enjoying time with my family. I have been married to my husband for 21 years and we have 3 children. Our oldest son is 18, our middle son is 15, and our daughter is 12. We also have 4 rescue animals! We feel so fortunate to call Gulf Breeze home.",
		"program": ["Kindergarten"],
		"imageTerm": "brennan-blanchard"
	},
	{
		"name": "Gerilyn Brueggemann",
		"role": ["teacher"],
		"bio": "Welcome and Blessings from 2nd Grade. My name is Gerilyn Brueggemann, known as Ms. G. I am the proud mother of 1 son, 3 daughters, 1 grandson, and 3 granddaughters. I have been blessed to teach at Good Shepherd for 5 years. I believe I was called to teach at GSLS. My love for children and their ability to learn brings great joy to me. Sharing my experiences, faith, beliefs, biblical teachings, and my love for Jesus is an integral part of education here. My goal at Good Shepherd is to make lifelong disciples of Jesus as it has been proven time and time again in my life, that Jesus has always been my rock-solid foundation. My prayer for 2022-2023 is that we will head into the future making disciples for life.",
		"program": ["First", "Second"],
		"imageTerm": "gerilyn"
	},
	{
		"name": "Sheena Cowper",
		"role": ["teacher"],
		"bio": "My name is Sheena Cowper. I come from a military family and enjoy traveling and experiencing new adventures with my children and family. I started teaching as a mental health prevention specialist in K-12 schools. After earning my Masters in Counseling and Psychology from Troy University, I began teaching undergraduate courses. I am excited about teaching at GSLS as it will provide more opportunities to spend time with my beautiful little humans as well as serving my purpose in education. God has given me the most surreal opportunity to teach and inspire little minds all in His name and love. I look forward to what the year will bring.",
		"program": ["Third", "Fourth", "Fifth"],
		"imageTerm": "sheena-cowper"
	},
	{
		"name": "Mary Jo Danforth",
		"role": ["teacher"],
		"bio": "My name is Mary Jo Danforth. I met my amazing husband Rob right after high school and we have been married 26 years. We have 3 beautiful daughters; Jordan (22), Courtney (17), and Addison (15). I am originally from Mobile, Alabama and moved to Navarre, Florida 22 years ago. I love the outdoors and have a huge love for all of God's creatures. In 1995, I received my degree in Business Management from Faulkner State College. I have since attended Daytona State College to revise my degree in Childhood Education. This will be my 7th year teaching VPK at Good Shepherd Lutheran School. I am excited to share my passion of teaching with each and every child. The excitement of the children as they grow in knowledge and develop a love for Jesus is priceless. I am looking forward to a fabulous school year working with amazing teachers, staff, and children.",
		"program": ["VPK", "Aftercare"],
		"imageTerm": "mary-jo-danforth"
	},
	{
		"name": "Alba Kerwin",
		"role": ["teacher"],
		"bio": "My name is Alba Kerwin. I was born in Honduras, Central America. I have been happily married to the most handsome retired Air Force man \"Bill\" for 39 years. We have three daughters, seven grandchildren, and seven grand-dogs. I have taught preschool for 30 years. It's been an honor to teach at Good Shepherd Lutheran School for 11 years, because I introduced the love of God to my young Super Stars through Music, Spanish, and Dramatic Play. I am the coolest teacher with a Mustang convertible ha..ha. God bless you all!",
		"program": ["Pre-K", "Third"],
		"imageTerm": "alba-kerwin"
	},
	{
		"name": "Mrs Holly",
		"role": ["administrator"],
		"bio": "My name is Mrs. Holly and I am the Administrator.\nI have lived in the area since 1986 with a short stint in the United Kingdom from January 1993 to June 1996.\nMy wonderful husband, Randy, and I have been married for 37 years! We have 3 amazing children, Randee Danielle (35), Harrison (33) and Hunter (22). We also have 4 adorable grandchildren, Desmond (9), Jenson (8), Jameson (5), and Everson (1).\nI have been at Good Shepherd Lutheran School for a total of 20 years. I started in 1998 as a Pre-K teacher and taught until 2000. I left in 2000 to have my son, Hunter. I returned in 2005 as the Administrative Assistant and became the Administrator in August of 2022.",
		"imageTerm": "mrs-holly"
	},
	{
		"name": "Heather McEachern",
		"role": ["teacher"],
		"program": ["VPK"],
		"bio": "Hi! My name is Heather McEachern. I moved to the beautiful beaches of Florida from a large farm in Mississippi in 2013. I met my husband, Chad, in 2015 and married him in 2020. He has 3 amazing children, Caleb (18), Celtsie (12), and Chayse (11) that I am honored to call my bonus babies. They hold a very special place in my heart. I have been an early childhood educator for 18 years and have loved every minute of it. I have been a VPK teacher at GSLS since 2014. I earned my CDA in 2015 and my Directors Credentials in 2019. I am currently enrolled in my second year at Daytona State College, and I am working toward my A.S. in Early Childhood Education. I became the VPK Director at GSLS in 2020. I enjoy teaching at GSLS, because not only do I get to mold little minds in their basic needs of education, but I also get to open their minds and hearts to the love and knowledge of Jesus Christ. I enjoy being the VPK Director, because I get to have a personal relationship with each child as well as their parents. I am looking forward to an amazing school year with our wonderful staff.",
		"imageTerm": "heather-mceachern"
	},
	{
		"name": "Krista Lewis",
		"role": ["teacher"],
		"program": ["Pre-K"],
		"bio": "Hello, my name is Krista Lewis, and I am thrilled to join as a PreK teacher's aid for the upcoming school year at Good Shepherd Lutheran School. I am passionate about working with children and have had the pleasure of getting to know many of our students and families through my involvement with Good Shepherd Lutheran Church. Over the years, I have been actively engaged in various roles, including teaching Sunday School, directing and volunteering for Vacation Bible School (VBS), and serving in Children and Family Ministries. I have also had the privilege of being part of the Youth Group and serving as a former member on the Good Shepherd Lutheran School Board. \nBeing around children and witnessing their growth has always been a source of joy for me. I find it incredibly rewarding to discover their unique personalities and help them learn and develop. I consider myself blessed to have this opportunity to serve the children and families at GSLS, and I am committed to creating a nurturing and engaging environment where every child can thrive. \nOutside of my professional life, I have been happily married to my wonderful husband, Mike, for twelve years. Together, we are blessed with three beautiful children: Trent, Ruby, and Jade. Our family cherishes moments spent together, whether it's enjoying quality time at the beach, playing board games, or watching movies. In 2016, we became proud members of Good Shepherd Lutheran Church and School, and since then, we have been actively involved in the community. \nI am eagerly anticipating what lies ahead for the students, staff, and families at Good Shepherd. It is my sincere belief that through collaboration, dedication, and the guidance of God, we can create an exceptional educational experience and a strong sense of community for all. I am thrilled to be a part of this journey and look forward to making a positive impact on the lives of our students."
	},
	{
		"name": "Jessica Stephens",
		"role": ["teacher"],
		"program": ["STEM", "PE"],
		"bio": "My name is Jessica Stephens aka Mrs. Jessi. My husband's name is Jon and he is currently serving in the USAF. I have two kiddos whom I love! My son Kyle is 8 and my daughter Kallie is 6. The majority of my career has been in the medical field, however, recently I have had a calling to work and serve with children. In my downtime I love to travel and I love trying new and local cuisine. I am such a FOODIE! I love to laugh and you will not catch me without my coffee! I am so excited to share this upcoming school year with each and every one of your children.",
		"imageTerm": "jessica-stephens"
	}
]
